### ISSUE TITLE
Setting project_type as Laravel in creating site.

### ISSUE THREAD

**Issue by best-lucky1030** [ploi-deploy/ploi-php-sdk#44]
I'd like to add project_type as Laravel when the site is created.
Seeing the ploi api in create resource, there is no option to set up the project_type.
So I couldn't set up the `$projectType = 'Laravel'`.
It was set up `null` as default, when I get the response from the created site.
How can I set the project_type using api, not manual.
![image](https://user-images.githubusercontent.com/89365150/145664191-b0a2e5c9-31e3-4b04-b194-98ee90bc2627.png)

I already made PR for this.

[](https://github.com/ploi-deploy/ploi-php-sdk/pull/45)

**Comment by fodderstompf** [comment]
@Cannonb4ll the API documentation doesn't list project_directory as an available parameter for create site request, is it actually possible already and just not listed or would be need to be added?

**Comment by Cannonb4ll** [comment]
@fodderstompf `project_type` is now available in the API, I'll write this out in the docs as well as the available options.

**Comment by best-lucky1030** [comment]
@Cannonb4ll 
Cool. It works for me. thanks a lot @Cannonb4ll 👍
