### ISSUE TITLE
Support for database "acknowledge" endpoint

### ISSUE THREAD

**Issue by jakebarshickf1nx** [ploi-deploy/ploi-php-sdk#6]
From a support ticket I had open with Ploi I learned about an undocumented "acknowledge" endpoint for databases. For my specific use case I have an app that dynamically creates new databases and this acknowledge command tells Ploi the database exists. Here's a paste from the response in my support ticket. 

```
POST https://ploi.io/api/servers/{server}/databases/acknowledge

With a parameter "name" as database name.
```

It would be useful for me if this could get added in. Thanks!

**Comment by Cannonb4ll** [comment]
Hi!

We've now also documented these rouets:

https://developers.ploi.io/databases/acknowledge-database
https://developers.ploi.io/databases/forget-database

You're more than welcome to submit a PR supporting the new database routes.

**Comment by jakebarshickf1nx** [comment]
Just submitted a PR. Let me know if there's any issues! #7

**Comment by Sekonda** [comment]
I've merged that PR in so I'm going to close this now.
